#!/usr/bin/python3.4

# Copyright 2015 Dalton Nikitas
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import re
import sys

# I know I could accomplish the same thing by parsing ps, but I wanted to learn about the structure of /proc

for proc in [p for p in os.listdir('/proc') if re.match('\d+', p)]:
    with open(os.path.join('/proc', proc, 'cmdline'), 'r') as fp:
        cmd = ' '.join(fp.read().split('\0'))
        if '/usr/bin/python /usr/local/bin/aws s3 sync' in cmd:
            sys.exit(int(proc))

sys.exit(0)

